#!/usr/bin/env python3
"""Check the Ethernet II trace matrix against the C# inventory (plan rule R2).

Inputs (relative to the repo root):
  docs/ethernet-port/cs-inventory.csv   generated by tools/ethport/make_inventory.sh
  docs/ethernet-port/TRACE-MATRIX.csv   one row per inventory id

TRACE-MATRIX.csv columns:
  id        inventory id, copied exactly
  status    PLANNED | PORTED | CLEANROOM | NOT_PORTED
  c_file    repo-relative C file (PLANNED/PORTED/CLEANROOM)
  c_symbol  C identifier that implements the row
  c_line    line of c_symbol in c_file (PORTED/CLEANROOM only)
  reason    why (required for NOT_PORTED; free text otherwise)
  approved  "Ronny" for NOT_PORTED rows, empty otherwise

Fails (exit 1) when:
  - an inventory id has no matrix row, or a matrix id is not in the inventory
  - an id appears twice in the matrix
  - status is not one of the four values
  - PORTED/CLEANROOM: c_file missing, or c_symbol not on c_line of c_file
  - PLANNED: c_file or c_symbol empty
  - NOT_PORTED: reason empty or approved != "Ronny"
  - with --final: any row still PLANNED
"""
import csv
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
INV = os.path.join(ROOT, "docs", "ethernet-port", "cs-inventory.csv")
MAT = os.path.join(ROOT, "docs", "ethernet-port", "TRACE-MATRIX.csv")
STATUSES = {"PLANNED", "PORTED", "CLEANROOM", "NOT_PORTED"}


def load(path, encoding="ascii"):
    with open(path, newline="", encoding=encoding) as f:
        return list(csv.DictReader(f))


def main():
    final = "--final" in sys.argv
    inv = load(INV, "utf-8")
    inv_ids = [r["id"] for r in inv]
    if len(set(inv_ids)) != len(inv_ids):
        dups = sorted({i for i in inv_ids if inv_ids.count(i) > 1})
        print("inventory has duplicate ids:", dups[:10])
        return 1
    if not os.path.exists(MAT):
        print("FAIL: %s missing; %d inventory rows unmapped" % (MAT, len(inv_ids)))
        return 1
    mat = load(MAT)
    errors = []
    seen = {}
    file_cache = {}
    for n, r in enumerate(mat, start=2):
        rid = r["id"]
        if rid in seen:
            errors.append("line %d: duplicate id %s (first at line %d)" % (n, rid, seen[rid]))
            continue
        seen[rid] = n
        st = r["status"].strip()
        if st not in STATUSES:
            errors.append("line %d: bad status %r" % (n, st))
            continue
        if st == "NOT_PORTED":
            if not r["reason"].strip() or r["approved"].strip() != "Ronny":
                errors.append("line %d: NOT_PORTED needs reason and approved=Ronny: %s" % (n, rid))
            continue
        if not r["c_file"].strip() or not r["c_symbol"].strip():
            errors.append("line %d: %s needs c_file and c_symbol: %s" % (n, st, rid))
            continue
        if st == "PLANNED":
            if final:
                errors.append("line %d: still PLANNED: %s" % (n, rid))
            continue
        path = os.path.join(ROOT, r["c_file"])
        if path not in file_cache:
            if not os.path.exists(path):
                errors.append("line %d: c_file not found: %s" % (n, r["c_file"]))
                continue
            with open(path, encoding="ascii") as f:
                file_cache[path] = f.read().split("\n")
        lines = file_cache[path]
        try:
            ln = int(r["c_line"])
        except ValueError:
            errors.append("line %d: c_line not a number: %r" % (n, r["c_line"]))
            continue
        sym = r["c_symbol"].strip()
        if ln < 1 or ln > len(lines) or not re.search(r"\b%s\b" % re.escape(sym), lines[ln - 1]):
            errors.append("line %d: %s not on %s:%d" % (n, sym, r["c_file"], ln))
    missing = [i for i in inv_ids if i not in seen]
    extra = [i for i in seen if i not in set(inv_ids)]
    for i in missing:
        errors.append("unmapped inventory id: %s" % i)
    for i in extra:
        errors.append("matrix id not in inventory: %s" % i)
    counts = {}
    for r in mat:
        counts[r["status"]] = counts.get(r["status"], 0) + 1
    print("inventory rows: %d  matrix rows: %d  by status: %s" % (len(inv_ids), len(mat), counts))
    if errors:
        for e in errors[:200]:
            print("FAIL:", e)
        if len(errors) > 200:
            print("... %d more" % (len(errors) - 200))
        print("matrix_check: %d errors" % len(errors))
        return 1
    print("matrix_check: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
