#!/bin/sh
# Regenerate m68kops.c / m68kops.h from the Musashi submodule.
# Run after moving external/Musashi to a new commit, then commit the output.
# Uses the build machine's C compiler (CC, default cc), never a cross compiler.
set -e
cd "$(dirname "$0")/.."

MUSASHI_DIR=external/Musashi
OUT_DIR=src/devices/ethernet/m68k/generated
CC=${CC:-cc}

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

"$CC" -o "$TMP_DIR/m68kmake" "$MUSASHI_DIR/m68kmake.c"
mkdir -p "$OUT_DIR"
"$TMP_DIR/m68kmake" "$OUT_DIR" "$MUSASHI_DIR/m68k_in.c"

COMMIT=$(git -C "$MUSASHI_DIR" rev-parse HEAD)
printf 'Generated by tools/gen_musashi_ops.sh from Musashi commit %s\n' "$COMMIT" \
    > "$OUT_DIR/MUSASHI_COMMIT.txt"
echo "Wrote $OUT_DIR/m68kops.c and m68kops.h (Musashi $COMMIT)"
