# Musashi 68000-family CPU core as a static library.
#
# The submodule external/Musashi is the RetroCoreLabs fork of Musashi
# (68000 bus error frame and execute-loop fixes, halted/stopped queries).
# Its opcode tables
# (m68kops.c / m68kops.h) are generated by Musashi's m68kmake tool; they are
# pre-generated and committed in src/devices/ethernet/m68k/generated/ so that
# cross builds never need to run a build-machine tool. Regenerate them with
# tools/gen_musashi_ops.sh after moving the submodule to a new commit.
#
# m68kfpu.c is not listed: m68kcpu.c includes it directly.
# m68kdasm.c (disassembler) is not listed: the card does not disassemble, and
# with M68K_LOG_ENABLE off the core does not call it.
#
# The configuration header is chosen with MUSASHI_CNF (m68k.h line 51). Set
# MUSASHI_CONFIG_HEADER to a project header before including this file;
# otherwise Musashi's own m68kconf.h is used.

set(MUSASHI_DIR "${CMAKE_CURRENT_LIST_DIR}/../external/Musashi")
set(MUSASHI_GEN_DIR "${CMAKE_CURRENT_LIST_DIR}/../src/devices/ethernet/m68k/generated")

if(NOT EXISTS "${MUSASHI_DIR}/m68kcpu.c")
    message(FATAL_ERROR "Musashi not found at ${MUSASHI_DIR} - run: git submodule update --init external/Musashi")
endif()

add_library(musashi STATIC
    ${MUSASHI_DIR}/m68kcpu.c
    ${MUSASHI_DIR}/softfloat/softfloat.c
    ${MUSASHI_GEN_DIR}/m68kops.c
)

target_include_directories(musashi PUBLIC
    ${MUSASHI_DIR}
    ${MUSASHI_GEN_DIR}
)

if(MUSASHI_CONFIG_HEADER)
    target_compile_definitions(musashi PUBLIC MUSASHI_CNF="${MUSASHI_CONFIG_HEADER}")
endif()

# Third-party code: do not apply the project's warning set to it.
if(NOT MSVC)
    target_compile_options(musashi PRIVATE -w)
endif()

if(NOT WIN32)
    target_link_libraries(musashi PUBLIC m)
endif()
